version: "3"
services:
  jekyll:
    image: jekyll/jekyll:pages
    container_name: jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "127.0.0.1:4000:4000"
    command: jekyll serve
    stdin_open: true
    tty: true
